apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-exporter-config
  namespace: monitoring
  labels:
    app: sql-exporter
data:
  config.yaml: |
    # SQL Exporter Configuration for Kubernetes
    databases:
      # PostgreSQL database
      postgres_main:
        driver: postgresql
        host: ${POSTGRES_HOST:-postgres-service}
        port: ${POSTGRES_PORT:-5432}
        database: ${POSTGRES_DATABASE:-postgres}
        username: ${POSTGRES_USER:-postgres}
        password: ${POSTGRES_PASS:-password}

      # MySQL database
      mysql_main:
        driver: mysql
        host: ${MYSQL_HOST:-mysql-service}
        port: ${MYSQL_PORT:-3306}
        database: ${MYSQL_DATABASE:-mysql}
        username: ${MYSQL_USER:-root}
        password: ${MYSQL_PASS:-password}

    queries:
      # PostgreSQL database metrics
      - name: postgres_database_metrics
        database: postgres_main
        interval: 300
        timeout: 45
        sql: |
          SELECT
            'database_size' as metric_name,
            datname as database_name,
            pg_database_size(datname) as value
          FROM pg_database
          WHERE datname NOT IN ('template0', 'template1', 'postgres')
          UNION ALL
          SELECT
            'active_connections' as metric_name,
            datname as database_name,
            COUNT(*) as value
          FROM pg_stat_activity
          WHERE state = 'active' AND datname IS NOT NULL
          GROUP BY datname
        metrics:
          - name: postgres_database_size_bytes
            help: "PostgreSQL database size in bytes"
            type: gauge
            labels: [database_name, metric_name]
            value_column: value

      # PostgreSQL connection monitoring
      - name: postgres_connections
        database: postgres_main
        interval: 30
        timeout: 15
        sql: |
          SELECT
            state,
            datname as database,
            COUNT(*) as connection_count
          FROM pg_stat_activity
          WHERE datname IS NOT NULL
          GROUP BY state, datname
        metrics:
          - name: postgres_connections_by_state
            help: "Number of PostgreSQL connections by state"
            type: gauge
            labels: [state, database]
            value_column: connection_count

      # PostgreSQL table statistics
      - name: postgres_table_stats
        database: postgres_main
        interval: 180
        timeout: 60
        sql: |
          SELECT
            schemaname,
            tablename,
            seq_scan,
            idx_scan,
            n_tup_ins as inserts,
            n_tup_upd as updates,
            n_tup_del as deletes,
            n_live_tup as live_tuples,
            n_dead_tup as dead_tuples
          FROM pg_stat_user_tables
          WHERE schemaname = 'public'
          LIMIT 20
        metrics:
          - name: postgres_table_sequential_scans_total
            help: "Total sequential scans on table"
            type: counter
            labels: [schemaname, tablename]
            value_column: seq_scan
          - name: postgres_table_index_scans_total
            help: "Total index scans on table"
            type: counter
            labels: [schemaname, tablename]
            value_column: idx_scan
          - name: postgres_table_live_tuples
            help: "Number of live tuples in table"
            type: gauge
            labels: [schemaname, tablename]
            value_column: live_tuples

    # Exporter configuration
    exporter:
      host: "0.0.0.0"
      port: 9090
      log_level: "INFO"