apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-exporter
  namespace: monitoring
  labels:
    app: sql-exporter
    version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: sql-exporter
  template:
    metadata:
      labels:
        app: sql-exporter
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: sql-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: sql-exporter
        image: sql-exporter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        # Exporter configuration
        - name: EXPORTER_HOST
          value: "0.0.0.0"
        - name: EXPORTER_PORT
          value: "9090"
        - name: LOG_LEVEL
          value: "INFO"
        - name: CONFIG_FILE
          value: "/app/config/config.yaml"

        # PostgreSQL connection
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: "postgres"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sql-exporter-secrets
              key: postgres-user
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: sql-exporter-secrets
              key: postgres-password

        # MySQL connection
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "mysql"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-exporter-secrets
              key: mysql-user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: sql-exporter-secrets
              key: mysql-password

        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: data
          mountPath: /app/data

        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

      volumes:
      - name: config
        configMap:
          name: sql-exporter-config
      - name: tmp
        emptyDir: {}
      - name: data
        emptyDir: {}

      restartPolicy: Always
      terminationGracePeriodSeconds: 30