apiVersion: v1
kind: ServiceAccount
metadata:
  name: sql-exporter
  namespace: monitoring
  labels:
    app: sql-exporter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sql-exporter
  labels:
    app: sql-exporter
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sql-exporter
  labels:
    app: sql-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sql-exporter
subjects:
- kind: ServiceAccount
  name: sql-exporter
  namespace: monitoring